inherit_from: .rubocop_todo.yml

# be rubocop --auto-gen-config

Rails:
  Enabled: true

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'vendor/**/*'

# Gemをアルファベッド順でなくてもok
Bundler/OrderedGems:
  Enabled: false

# Gemfileの1行目のsourceをSourceではなくてもok
Naming/FileName:
  Exclude:
    - 'Gemfile'

# コメントで日本語使用ok
Style/AsciiComments:
  Enabled: false

# ブロックコメントはok
Style/BlockComments:
  Enabled: false

# class moduleに対するコメントはなくてok
Style/Documentation:
  Enabled: false

# frozen string leteral commentがなくてもok(RubyのStringリテラルが勝手にfreezeされてimmutableになる。 Ruby3系では基本的にimmutableになる予定)
Style/FrozenStringLiteralComment:
  Enabled: false

# " 'を区別しなくてok
Style/StringLiterals:
  Enabled: false

# %i(Ruby Python PHP)  => [:Ruby, :Python, :PHP] みたいに書かなくてok
Style/SymbolArray:
  Enabled: false

# 1行に文字120まで書ける
Metrics/LineLength:
  Max: 150

# ブロックの中身の行数50行までok
Metrics/BlockLength:
  Max: 50

# module_name::class_nameみたいな書き方ok
Style/ClassAndModuleChildren:
  Enabled: false

# メソッド内のライン20行までok
Metrics/MethodLength:
  Max: 20

# メソッドをもっと細かく分けるのは後回しでok
Metrics/AbcSize:
 Enabled: false

# nation.rbのhas_many :foreignersのオプションとしてdependentをつけなくてもok
HasManyOrHasOneDependent:
    Exclude:
      - 'app/models/nation.rb'

# if文を1行で書かなくてもok
Style/GuardClause:
   Enabled: false
